import React from "react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900">
      <header className="border-b border-gray-200 py-4 px-6 flex items-center justify-between">
        <div className="text-2xl font-bold">ScheduleBuddy</div>
        <div className="flex items-center space-x-4">
          <button className="text-sm font-medium">Sign in</button>
          <button className="bg-black text-white px-4 py-2 rounded-md text-sm font-medium">
            Get started
          </button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold mb-6">Privacy Policy</h1>
        <p className="text-gray-600 mb-2">Effective date: 04/24/2025</p>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
          <p className="mb-4">Welcome to ScheduleBuddy.cloud.</p>
          <p className="mb-4">
            ScheduleBuddy.cloud (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates https://schedulebuddy.cloud (hereinafter
            referred to as &quot;Service&quot;).
          </p>
          <p className="mb-4">
            Our Privacy Policy governs your visit to https://schedulebuddy.cloud,
            and explains how we collect, safeguard and disclose information that
            results from your use of our Service.
          </p>
          <p className="mb-4 justify-evenly">
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </p>

          <p className="mb-4 justify-evenly">
            If you do not agree with (or cannot comply with) Agreements, then
            you may not use the Service, but please let us know by emailing at
            support@schedulebuddy.cloud so we can try to find a solution. These
            Terms apply to all visitors, users and others who wish to access or
            use Service.
          </p>

          <p className="mb-4 justify-evenly">
            Thank you for being responsible.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Definitions</h2>
          <p className="mb-4">
            SERVICE means the https://schedulebuddy.cloud website operated by
            schedulebuddy.cloud.
          </p>
          <p className="mb-4">
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
          <p className="mb-4">
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit).
          </p>
          <p className="mb-4">
            COOKIES are small files stored on your device (computer or mobile
            device).
          </p>
          <p className="mb-4">
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
          </p>

          <p className="mb-4">
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
          </p>

          <p className="mb-4">
            THE USER is the individual using our Service. The User corresponds
            to the Data Subject, who is the subject of Personal Data.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">
            Information Collection and Use
          </h2>
          <p className="mb-4">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
          {/* <ul className="list-disc list-inside mb-4 space-y-2">
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter,” “spam,” or any other similar solicitation.</li>
            <li>To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity.</li>
            <li>In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful.</li>
            <li>To engage in any conduct that restricts or inhibits anyone’s use or enjoyment of Service.</li>
          </ul>
          <p className="mb-4">
            Additionally, you agree not to:
          </p>
          <ul className="list-disc list-inside mb-4 space-y-2">
            <li>Use Service in any manner that could disable, overburden, damage, or impair Service.</li>
            <li>Use any robot, spider, or other automatic device, process, or means to access Service for any purpose.</li>
            <li>Use any manual process to monitor or copy any of the material on Service without our prior written consent.</li>
            <li>Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</li>
            <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service.</li>
            <li>Attack Service via a denial-of-service attack or a distributed denial-of-service attack.</li>
            <li>Otherwise attempt to interfere with the proper working of Service.</li>
          </ul> */}
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Definitions</h2>

          <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
          <p className="mb-4">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (&quot;Personal Data&quot;). Personally identifiable
            information may include, but is not limited to:
          </p>

          <h4 className="text-lg font-semibold mb-2">Cookies and Usage Data</h4>
          <p className="mb-4">
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or by
            emailing at support@schedulebuddy.cloud.
          </p>

          <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
          <p className="mb-4">
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (&quot;Usage Data&quot;).
          </p>

          <p className="mb-4">
            This Usage Data may include information such as your computer&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>

          <p className="mb-4">
            When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </p>

          <h4 className="text-lg font-semibold mb-2">Tracking Cookies Data</h4>
          <p className="mb-4">
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <p className="mb-4">
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.
          </p>
          <p className="mb-4">
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Use of Data</h2>
          <p className="mb-4">
            Schedulebuddy.cloud uses the collected data for various purposes:
          </p>
          <ul className="list-disc list-inside mb-4 space-y-2">
            <li>To provide and maintain our Service;</li>
            <li>To notify you about changes to our Service;</li>
            <li>
              To allow you to participate in interactive features of our Service
              when you choose to do so
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues;</li>
            <li>To fulfill any other purpose for which you provide it</li>
            <li>
              To carry out our obligations and enforce our rights arising from
              any contracts entered into between you and us, including for
              billing and collection
            </li>
            <li>
              To provide you with notices about your account and/or
              subscription, including expiration and renewal notices,
              email-instructions, etc.
            </li>
            <li>
              To provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information
            </li>
            <li>
              In any other way we may describe when you provide the information
            </li>
            <li>For any other purpose with your consent.</li>
          </ul>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Retention of Data</h2>
          <p className="mb-4">
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </p>
          <p className="mb-4">
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period of time, except when
            this data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Transfer of Data</h2>
          <p className="mb-4">
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </p>
          <p className="mb-4">
            If you are located outside United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to United States and process it there.
          </p>
          <p className="mb-4">
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </p>

          <p>
            Schedulebuddy.cloud will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will take
            place to an organisation or a country unless there are adequate
            controls in place including the security of your data and other
            personal information.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Disclosure of Data</h2>
          <p className="mb-4">
            We may disclose personal information that we collect, or you
            provide:
          </p>

          <h4 className="text-lg font-semibold mb-2">
            Disclosure for Law Enforcement.
          </h4>
          <p className="mb-4">
            Under certain circumstances, we may be required to disclose your
            Personal Data if required to do so by law or in response to valid
            requests by public authorities.
          </p>
          <h4 className="text-lg font-semibold mb-2">Business Transaction.</h4>
          <p className="mb-4">
            If we or our subsidiaries are involved in a merger, acquisition or
            asset sale, your Personal Data may be transferred.
          </p>
          <p className="mb-4">
            Other cases. We may disclose your information also:
          </p>
          <ul className="list-disc list-inside mb-4 space-y-2">
            <li>To our subsidiaries and affiliates;</li>
            <li>
              To contractors, service providers, and other third parties we use
              to support our business;
            </li>
            <li>To fulfill the purpose for which you provide it;</li>
            <li>
              For the purpose of including your company’s logo on our website;
            </li>
            <li>
              For any other purpose disclosed by us when you provide the
              information;
            </li>
            <li>With your consent in any other cases;</li>
            <li>
              If we believe disclosure is necessary or appropriate to protect
              the rights, property, or safety of the Company, our customers, or
              others.
            </li>
          </ul>

        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-semibold mb-4">Security of Data</h2>
          <p className="mb-4">
          The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
          
        </section>

        <section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
  <p className="mb-4">
    If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at{' '}
    <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">
      this link
    </a>.
  </p>
  <p className="mb-4">
    We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
  </p>
  <p className="mb-4">
    If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at{' '}
    <a href="mailto:support@schedulebuddy.cloud" className="text-blue-600 underline">
      support@schedulebuddy.cloud
    </a>.
  </p>
  <p className="mb-4">
    In certain circumstances, you have the following data protection rights:
  </p>
  <ul className="list-disc list-inside mb-4 space-y-2">
    <li>The right to access, update or to delete the information we have on you;</li>
    <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
    <li>The right to object. You have the right to object to our processing of your Personal Data;</li>
    <li>The right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
    <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
    <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
  </ul>
  <p className="mb-4">
    Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.
  </p>
  <p className="mb-4">
    You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
  <p className="mb-4">
    CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at{' '}
    <a href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">
      this link
    </a>.
  </p>
  <p className="mb-4">
    According to CalOPPA we agree to the following:
  </p>
  <ul className="list-disc list-inside mb-4 space-y-2">
    <li>Users can visit our site anonymously;</li>
    <li>Our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website;</li>
    <li>Users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
    <li>Users are able to change their personal information by emailing us at{' '}
      <a href="mailto:support@schedulebuddy.cloud" className="text-blue-600 underline">
      support@schedulebuddy.cloud
      </a>.
    </li>
  </ul>
  <h3 className="text-xl font-semibold mb-2">Our Policy on “Do Not Track” Signals:</h3>
  <p className="mb-4">
    We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
  </p>
  <p className="mb-4">
    You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h2>
  <p className="mb-4">
    If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
  </p>
  <ul className="list-disc list-inside mb-4 space-y-2">
    <li>The categories of personal information we have collected about you.</li>
    <li>The categories of sources from which we collect your personal information.</li>
    <li>The business or commercial purpose for collecting or selling your personal information.</li>
    <li>The categories of third parties with whom we share personal information.</li>
    <li>The specific pieces of personal information we have collected about you.</li>
    <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
    <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
  </ul>
  <p className="mb-4">
    Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
  </p>
  <p className="mb-4">
    <strong>To delete your personal information:</strong> If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
  </p>
  <p className="mb-4">
    <strong>To stop selling your personal information:</strong> We don&apos;t sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
  </p>
  <p className="mb-4">
    Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
  </p>
  <p className="mb-4">
    To exercise your California data protection rights described above, please send your request(s) by one of the following means:
  </p>
  <ul className="list-disc list-inside mb-4 space-y-2">
    <li>By email: <a href="mailto:support@schedulebuddy.cloud" className="text-blue-600 underline">support@schedulebuddy.cloud</a></li>
  </ul>
  <p className="mb-4">
    Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Service Providers</h2>
  <p className="mb-4">
    We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.
  </p>
  <p className="mb-4">
    These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Links to Other Sites</h2>
  <p className="mb-4">
    Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.
  </p>
  <p className="mb-4">
    We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Children&apos;s Privacy</h2>
  <p className="mb-4">
    Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).
  </p>
  <p className="mb-4">
    We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
  <p className="mb-4">
    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
  </p>
  <p className="mb-4">
    We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.
  </p>
  <p className="mb-4">
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
  </p>
</section>

<section className="mt-10">
  <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
  <p className="mb-4">
    If you have any questions about this Privacy Policy, please contact us:
  </p>
  <p className="mb-4">
    By email:&nbsp;
    <a href="mailto:support@schedulebuddy.cloud" className="text-blue-600 underline">
      support@schedulebuddy.cloud
    </a>
  </p>
</section>


       
      </main>
    </div>
  );
}
